repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: sort-simple-yaml

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        args: [--skip-string-normalization]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        files: "."
        args: [--profile, black, --filter-files]
